@startuml
actor actor as user
participant graphics as view
participant agent as agent
participant behavior as steeringBehavior
participant leaderFollower as lF

user -> lF: user defines scenario
activate lF
activate view
activate agent
activate steeringBehavior
note left: anytime
user -> view:  set mouse position
loop intinite    
    lF -> view: request mouse position    
    view --> lF: gives mouse position        
    
    alt if agent is leader
        lF -> agent: set agent target position
        lF -> steeringBehavior: request seek force for agent        
        steeringBehavior --> lF: gives seek force
        lF -> agent: set agent force
        agent -> agent: calculates next position
        lF -> view: draw leaders name
    else follower agents
        loop for all agents 
        lF -> agent: set target point
        lF ->steeringBehavior: request separation force
        steeringBehavior --> lF: gives separation force
        lF ->steeringBehavior: request seek force
        steeringBehavior --> lF: gives seek force
        agent -> agent: calculate next position
        lF -> agent: set arrive behavior
        agent -> agent: calculate next position
        end
    end
    lF -> view: draw agents
    lF -> view: draw title
    lF -> view: refresh
end
user -> view: stop program
deactivate lF
deactivate view
deactivate agent
deactivate steeringBehavior
@enduml