@startuml
actor actor as user
participant graphics as view
participant agent as agent
participant behavior as steeringBehavior
participant leaderFollower as lF

user -> lF: user defines scenario
activate lF
activate view
activate agent
activate steeringBehavior
note left: anytime
user -> view:  set mouse position
loop triggered with 20ms periodic event
    loop for all agents    
        alt if agent is leader
            lF -> view: request mouse position    
            view --> lF: gives mouse position        
            lF -> agent: set agent target position
            lF -> steeringBehavior: request seek force for target pos.
            steeringBehavior --> lF: gives seek force
            lF -> agent: set force            
            lF -> view: draw leaders name
        else follower agents        
            lF -> agent: set target point 
            lf -> agent: transform target point
            lF ->steeringBehavior: request separation force
            steeringBehavior --> lF: gives separation force
            lF ->agent: add force            
        end
    end
    lF -> agent:set arrive bevahior
    agent -> agent: calculates next position
    lF -> view: draw agents
    lF -> view: draw title
    lF -> view: refresh
end
user -> view: stop program
deactivate lF
deactivate view
deactivate agent
deactivate steeringBehavior
@enduml