@startuml
actor actor as user
participant graphics as view
participant agent as agent
participant behavior as steeringBehavior
participant mouseFollower as mF

user -> mF: user defines scenario
activate mF
activate view
activate agent
activate steeringBehavior
note left: anytime
user -> view:  set mouse position
loop triggered with 20ms periodic event
    loop for all agents
        mF -> view: request mouse position
        view --> mF: gives mouse position
        mF -> agent: set agent target position
        mF -> steeringBehavior: request seek force for agent
        steeringBehavior --> mF: gives seek force
        mF -> agent: set agent force
        mF -> agent: set arriving behavior
    end    
    agent -> agent: calculate next position    
    mF -> view: draw agents
    mF -> view: draw title
    mF -> view: refresh
end
user -> view: stop program
deactivate mF
deactivate view
deactivate agent
deactivate steeringBehavior
@enduml