@startuml
actor actor as user
participant graphics as view
participant flow as fl
participant agent as agent
participant behavior as steeringBehavior
participant windy as wd

user -> wd: user defines scenario
activate wd
activate view
activate fl
activate agent
activate steeringBehavior
note left: anytime
user -> view:  set mouse position
loop triggered with 20ms periodic event   
    loop for all agents
        wd -> fl: request gravity flow field;
        fl --> wd: gives gravity        
        wd -> steeringBehavior: request gravity force
        steeringBehavior --> wd: gives gravity force
        wd -> fl: request wind flow field;
        fl --> wd: gives wind
        wd -> steeringBehavior: request wind force
        steeringBehavior --> wd: gives wind force
        wd -> agent: set force
    end    

    agent -> agent: calculate next position    
    wd -> view: draw agents
    wd -> view: draw title
    wd -> view: refresh
end
user -> view: stop program
deactivate wd
deactivate view
deactivate agent
deactivate fl
deactivate steeringBehavior
@enduml